name: clang-format Check

on: [ pull_request ]

jobs:
  formatting-check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        path:
          - src
          - include

    steps:
      - uses: actions/checkout@v4
      - uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: 18
          check-path: ${{ matrix.path }}
